# Generated by Django 4.2.7 on 2026-03-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_subject_description_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('subject', 'title')},
        ),
    ]
