# Generated by Django 4.2.7 on 2026-03-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_order_alter_lesson_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
